import React from 'react';
import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@react-pdf/renderer';
import {
  UnderwritingFormData,
  PropertyComparable,
  CalculatedResults,
  CompSelectionState,
} from '@/types/underwriting';
import PDFMetricsSection from './PDFMetricsSection';
import PDFGaryOpinion from './PDFGaryOpinion';
import PDFCompsSection from './PDFCompsSection';
import PDFCalculationBreakdown from './PDFCalculationBreakdown';
import { formatDateForPDF, BRAND_COLORS, FONT_SIZES, SPACING } from '@/lib/pdf/pdfUtils';

interface UnderwritingReportPDFProps {
  formData: UnderwritingFormData;
  garyCalculations: CalculatedResults;
  garyAsIsValue: number;
  finalScore: number;
  garyOpinion: string;
  comps: PropertyComparable[];
  compSelectionState: CompSelectionState[];
}

export default function UnderwritingReportPDF({
  formData,
  garyCalculations,
  garyAsIsValue,
  finalScore,
  garyOpinion,
  comps,
  compSelectionState,
}: UnderwritingReportPDFProps) {
  const generatedDate = formatDateForPDF(new Date());

  return (
    <Document
      title={`Glass Loans Underwriting Report - ${formData.propertyAddress}`}
      author="Glass Loans"
      subject="Real Estate Underwriting Analysis"
      creator="Glass Loans Pro Dashboard"
      producer="Glass Loans"
      keywords="underwriting, real estate, ARV, loan analysis"
      creationDate={new Date()}
    >
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header} fixed>
          <View style={styles.headerLeft}>
            <Text style={styles.headerLogo}>Glass Loans</Text>
            <Text style={styles.headerSubtitle}>Underwriting Report</Text>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.headerDate}>{generatedDate}</Text>
          </View>
        </View>

        {/* Content */}
        <View style={styles.content}>
          {/* Section 1: Score & Metrics */}
          <PDFMetricsSection
            propertyAddress={formData.propertyAddress}
            score={finalScore}
            garyCalculations={garyCalculations}
            garyAsIsValue={garyAsIsValue}
          />

          {/* Section 2: Gary's Opinion */}
          <View break>
            <PDFGaryOpinion opinion={garyOpinion} />
          </View>

          {/* Section 3: Comps (without map) */}
          <View break>
            <PDFCompsSection
              comps={comps}
              compSelectionState={compSelectionState}
            />
          </View>

          {/* Section 4: Detailed Calculations */}
          <View break>
            <PDFCalculationBreakdown
              formData={formData}
              calculations={garyCalculations}
            />
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Generated by Glass Loans Pro | {formData.propertyAddress}
          </Text>
          <Text
            style={styles.footerPageNumber}
            render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  );
}

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: BRAND_COLORS.white,
    paddingTop: 60, // Space for fixed header
    paddingBottom: 50, // Space for fixed footer
    paddingHorizontal: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: SPACING.md,
    paddingHorizontal: 40,
    borderBottomWidth: 2,
    borderBottomColor: BRAND_COLORS.primary,
    backgroundColor: BRAND_COLORS.white,
  },
  headerLeft: {
    flexDirection: 'column',
  },
  headerLogo: {
    fontSize: FONT_SIZES.heading,
    fontWeight: 'bold',
    color: BRAND_COLORS.primary,
  },
  headerSubtitle: {
    fontSize: FONT_SIZES.small,
    color: BRAND_COLORS.gray,
    marginTop: 2,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  headerDate: {
    fontSize: FONT_SIZES.small,
    color: BRAND_COLORS.gray,
  },
  content: {
    flexGrow: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: SPACING.sm,
    paddingHorizontal: 40,
    borderTopWidth: 1,
    borderTopColor: BRAND_COLORS.lightGray,
    backgroundColor: BRAND_COLORS.white,
  },
  footerText: {
    fontSize: FONT_SIZES.caption,
    color: BRAND_COLORS.gray,
  },
  footerPageNumber: {
    fontSize: FONT_SIZES.caption,
    color: BRAND_COLORS.gray,
  },
});
